language: ruby

addons:
  apt:
    packages:
      - docker-ce

script:
    - docker build -t u6kapps/redmine .

after_success:
    - if [ -n "$TRAVIS_TAG" ]; then
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
          docker tag u6kapps/redmine u6kapps/redmine:$TRAVIS_TAG;
          docker push u6kapps/redmine;
      else
          echo skip docker push;
      fi
