version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "REDMINE_DB_POSTGRES=db"
      - "REDMINE_DB_USERNAME=db_user"
      - "REDMINE_DB_PASSWORD=db_pass"
      - "REDMINE_DB_DATABASE=redmine"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pass"
      - "POSTGRES_DB=redmine"
