# Homebrewを最新にする。
update

# インストール済みソフトウェアを最新にする。
upgrade

# リポジトリを追加
tap homebrew/binary
tap caskroom/cask

# インストール
install git
install wget
install openssl

# インストール(.dmg)
install brew-cask
cask install google-chrome
cask install virtualbox
cask install vagrant
cask install sourcetree
cask install skype
cask install skitch
cask install bettertouchtool
cask install dropbox
cask install appcleaner
cask install hyperswitch
cask install google-japanese-ime
cask install onyx
cask install java
cask install coteditor
cask install handbrake
cask install vlc
cask install the-unarchiver
cask install diskwave
cask install cyberduck
cask install genymotion
cask install thunderbird

# 古いバージョンを削除
cleanup
