version: 2
jobs:
    build:
        working_directory: /repo
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build docker image
                command: docker build -t u6kapps/redmine .
            - deploy:
                name: Push docker image
                command: |
                    if [ -n "${CIRCLE_TAG}" ]; then
                        docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
                        docker tag u6kapps/redmine u6kapps/redmine:${CIRCLE_TAG}
                        docker push u6kapps/redmine
                    else
                        echo skip deploy
                    fi
